# Generated by Django 3.1.3 on 2021-08-10 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('cgpa_cutoff', models.FloatField(blank=True)),
                ('resume', models.TextField(blank=True)),
                ('batch', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('period', models.CharField(max_length=255)),
                ('ot_summary', models.TextField(blank=True)),
                ('ot_question1', models.TextField(blank=True, null=True)),
                ('ot_question1_link', models.TextField(blank=True, default='NONE', null=True)),
                ('ot_question2', models.TextField(blank=True, null=True)),
                ('ot_question2_link', models.TextField(blank=True, null=True)),
                ('ot_question3', models.TextField(blank=True, null=True)),
                ('ot_question3_link', models.TextField(blank=True, null=True)),
                ('ot_question4', models.TextField(blank=True, null=True)),
                ('ot_question4_link', models.TextField(blank=True, null=True)),
                ('round1_details', models.TextField(blank=True, null=True)),
                ('round2_details', models.TextField(blank=True, null=True)),
                ('round3_details', models.TextField(blank=True, null=True)),
                ('final_summary', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
