# Generated by Django 2.1.5 on 2021-08-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('cgpa', models.FloatField(blank=True)),
                ('company', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('period', models.CharField(max_length=255)),
                ('ot_summary', models.TextField(blank=True)),
                ('ot_question1', models.TextField(blank=True)),
                ('ot_question2', models.TextField(blank=True)),
                ('ot_question3', models.TextField(blank=True)),
                ('ot_question4', models.TextField(blank=True)),
                ('round1_details', models.TextField(blank=True)),
                ('round1_links', models.TextField(blank=True)),
                ('round2_details', models.TextField(blank=True)),
                ('round2_links', models.TextField(blank=True)),
                ('round3_details', models.TextField(blank=True)),
                ('round3_links', models.TextField(blank=True)),
                ('final_summary', models.TextField(blank=True)),
            ],
        ),
    ]
