# Generated by Django 3.2.6 on 2021-08-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='cgpa',
            new_name='cgpa_cutoff',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='round1_links',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='round2_links',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='round3_links',
        ),
        migrations.AddField(
            model_name='experience',
            name='ot_question1_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='ot_question2_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='ot_question3_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='ot_question4_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
