# Generated by Django 3.2.6 on 2021-08-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20210812_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
